<?php
/**
 * CampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class
 * @description Campaign
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {
    }

    /**
     * Test attribute "active_questions"
     */
    public function testPropertyActiveQuestions()
    {
    }

    /**
     * Test attribute "ad"
     */
    public function testPropertyAd()
    {
    }

    /**
     * Test attribute "advisor_tree"
     */
    public function testPropertyAdvisorTree()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "exclude_products_not_in_markets"
     */
    public function testPropertyExcludeProductsNotInMarkets()
    {
    }

    /**
     * Test attribute "exclude_products_not_in_range"
     */
    public function testPropertyExcludeProductsNotInRange()
    {
    }

    /**
     * Test attribute "feedback_texts"
     */
    public function testPropertyFeedbackTexts()
    {
    }

    /**
     * Test attribute "flavour"
     */
    public function testPropertyFlavour()
    {
    }

    /**
     * Test attribute "hits"
     */
    public function testPropertyHits()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "target"
     */
    public function testPropertyTarget()
    {
    }
}
