<?php
/**
 * FacetElementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FacetElementTest Class Doc Comment
 *
 * @category    Class
 * @description FacetElement
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FacetElementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FacetElement"
     */
    public function testFacetElement()
    {
    }

    /**
     * Test attribute "absolute_max_value"
     */
    public function testPropertyAbsoluteMaxValue()
    {
    }

    /**
     * Test attribute "absolute_min_value"
     */
    public function testPropertyAbsoluteMinValue()
    {
    }

    /**
     * Test attribute "cluster_level"
     */
    public function testPropertyClusterLevel()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "preview_image_url"
     */
    public function testPropertyPreviewImageUrl()
    {
    }

    /**
     * Test attribute "search_params"
     */
    public function testPropertySearchParams()
    {
    }

    /**
     * Test attribute "selected"
     */
    public function testPropertySelected()
    {
    }

    /**
     * Test attribute "selected_max_value"
     */
    public function testPropertySelectedMaxValue()
    {
    }

    /**
     * Test attribute "selected_min_value"
     */
    public function testPropertySelectedMinValue()
    {
    }

    /**
     * Test attribute "show_distance"
     */
    public function testPropertyShowDistance()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "total_hits"
     */
    public function testPropertyTotalHits()
    {
    }
}
