<?php
/**
 * FacetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FacetTest Class Doc Comment
 *
 * @category    Class
 * @description Facet
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FacetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Facet"
     */
    public function testFacet()
    {
    }

    /**
     * Test attribute "associated_field_name"
     */
    public function testPropertyAssociatedFieldName()
    {
    }

    /**
     * Test attribute "decimal_places"
     */
    public function testPropertyDecimalPlaces()
    {
    }

    /**
     * Test attribute "detailed_links"
     */
    public function testPropertyDetailedLinks()
    {
    }

    /**
     * Test attribute "elements"
     */
    public function testPropertyElements()
    {
    }

    /**
     * Test attribute "filter_style"
     */
    public function testPropertyFilterStyle()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "selected_elements"
     */
    public function testPropertySelectedElements()
    {
    }

    /**
     * Test attribute "selection_type"
     */
    public function testPropertySelectionType()
    {
    }

    /**
     * Test attribute "show_preview_images"
     */
    public function testPropertyShowPreviewImages()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }
}
