<?php
/**
 * PagingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PagingTest Class Doc Comment
 *
 * @category    Class
 * @description Paging
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PagingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Paging"
     */
    public function testPaging()
    {
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "default_hits_per_page"
     */
    public function testPropertyDefaultHitsPerPage()
    {
    }

    /**
     * Test attribute "hits_per_page"
     */
    public function testPropertyHitsPerPage()
    {
    }

    /**
     * Test attribute "next_link"
     */
    public function testPropertyNextLink()
    {
    }

    /**
     * Test attribute "page_count"
     */
    public function testPropertyPageCount()
    {
    }

    /**
     * Test attribute "previous_link"
     */
    public function testPropertyPreviousLink()
    {
    }
}
