<?php
/**
 * ResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ResultTest Class Doc Comment
 *
 * @category    Class
 * @description Result
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Result"
     */
    public function testResult()
    {
    }

    /**
     * Test attribute "answers"
     */
    public function testPropertyAnswers()
    {
    }

    /**
     * Test attribute "article_number_search"
     */
    public function testPropertyArticleNumberSearch()
    {
    }

    /**
     * Test attribute "bread_crumb_trail"
     */
    public function testPropertyBreadCrumbTrail()
    {
    }

    /**
     * Test attribute "campaigns"
     */
    public function testPropertyCampaigns()
    {
    }

    /**
     * Test attribute "facets"
     */
    public function testPropertyFacets()
    {
    }

    /**
     * Test attribute "field_roles"
     */
    public function testPropertyFieldRoles()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }

    /**
     * Test attribute "follow_search"
     */
    public function testPropertyFollowSearch()
    {
    }

    /**
     * Test attribute "geo"
     */
    public function testPropertyGeo()
    {
    }

    /**
     * Test attribute "hits"
     */
    public function testPropertyHits()
    {
    }

    /**
     * Test attribute "paging"
     */
    public function testPropertyPaging()
    {
    }

    /**
     * Test attribute "score_first_hit"
     */
    public function testPropertyScoreFirstHit()
    {
    }

    /**
     * Test attribute "score_last_hit"
     */
    public function testPropertyScoreLastHit()
    {
    }

    /**
     * Test attribute "search_control_params"
     */
    public function testPropertySearchControlParams()
    {
    }

    /**
     * Test attribute "search_params"
     */
    public function testPropertySearchParams()
    {
    }

    /**
     * Test attribute "single_word_results"
     */
    public function testPropertySingleWordResults()
    {
    }

    /**
     * Test attribute "sort_items"
     */
    public function testPropertySortItems()
    {
    }

    /**
     * Test attribute "split_documents"
     */
    public function testPropertySplitDocuments()
    {
    }

    /**
     * Test attribute "timed_out"
     */
    public function testPropertyTimedOut()
    {
    }

    /**
     * Test attribute "took_loop54"
     */
    public function testPropertyTookLoop54()
    {
    }

    /**
     * Test attribute "took_total"
     */
    public function testPropertyTookTotal()
    {
    }

    /**
     * Test attribute "took_worldmatch"
     */
    public function testPropertyTookWorldmatch()
    {
    }

    /**
     * Test attribute "total_hits"
     */
    public function testPropertyTotalHits()
    {
    }
}
