<?php
/**
 * SingleWordSearchResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * SingleWordSearchResultTest Class Doc Comment
 *
 * @category    Class
 * @description SingleWordSearchResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleWordSearchResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SingleWordSearchResult"
     */
    public function testSingleWordSearchResult()
    {
    }

    /**
     * Test attribute "preview_records"
     */
    public function testPropertyPreviewRecords()
    {
    }

    /**
     * Test attribute "search_params"
     */
    public function testPropertySearchParams()
    {
    }

    /**
     * Test attribute "total_hits"
     */
    public function testPropertyTotalHits()
    {
    }

    /**
     * Test attribute "word"
     */
    public function testPropertyWord()
    {
    }
}
