<?php
/**
 * SuggestionResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * SuggestionResultTest Class Doc Comment
 *
 * @category    Class
 * @description Contains a list of suggestions, the field role to field name mapping and the information if an article number search is possible.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SuggestionResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SuggestionResult"
     */
    public function testSuggestionResult()
    {
    }

    /**
     * Test attribute "article_number_search_allowed"
     */
    public function testPropertyArticleNumberSearchAllowed()
    {
    }

    /**
     * Test attribute "field_roles"
     */
    public function testPropertyFieldRoles()
    {
    }

    /**
     * Test attribute "geo"
     */
    public function testPropertyGeo()
    {
    }

    /**
     * Test attribute "split_documents"
     */
    public function testPropertySplitDocuments()
    {
    }

    /**
     * Test attribute "suggestions"
     */
    public function testPropertySuggestions()
    {
    }
}
