<?php
/**
 * ClusterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClusterApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClusterApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fullSyncUsingPOST
     *
     * Fully synchronize the worldmatch database of this node..
     *
     */
    public function testFullSyncUsingPOST()
    {
    }

    /**
     * Test case for getDatabaseStateUsingGET
     *
     * Show the current state of the worldmatch database..
     *
     */
    public function testGetDatabaseStateUsingGET()
    {
    }

    /**
     * Test case for getImportStateUsingGET
     *
     * Show the import state of this node..
     *
     */
    public function testGetImportStateUsingGET()
    {
    }

    /**
     * Test case for getStateUsingGET
     *
     * Get the cluster state. Includes database & import & cache state..
     *
     */
    public function testGetStateUsingGET()
    {
    }

    /**
     * Test case for pruneUsingPOST
     *
     * Prune delta updates..
     *
     */
    public function testPruneUsingPOST()
    {
    }

    /**
     * Test case for syncDatabaseUsingPOST
     *
     * Synchronize the worldmatch database of this node..
     *
     */
    public function testSyncDatabaseUsingPOST()
    {
    }
}
