<?php
/**
 * ManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeLogLevelUsingPOST
     *
     * Changes the log level.
     *
     */
    public function testChangeLogLevelUsingPOST()
    {
    }

    /**
     * Test case for flushCacheUsingPOST
     *
     * Flush the cache.
     *
     */
    public function testFlushCacheUsingPOST()
    {
    }

    /**
     * Test case for flushLogsUsingPOST
     *
     * Flush the log files.
     *
     */
    public function testFlushLogsUsingPOST()
    {
    }

    /**
     * Test case for getExpirationMessagesUsingGET
     *
     * Get expiration messages.
     *
     */
    public function testGetExpirationMessagesUsingGET()
    {
    }

    /**
     * Test case for reloadConfigurationUsingPOST
     *
     * Reload the configuration.
     *
     */
    public function testReloadConfigurationUsingPOST()
    {
    }

    /**
     * Test case for resetLogLevelUsingPOST
     *
     * Resets the log level to the original level.
     *
     */
    public function testResetLogLevelUsingPOST()
    {
    }
}
