<?php
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for categoryNavigationUsingGET
     *
     * Category ASN for Navigation.
     *
     */
    public function testCategoryNavigationUsingGET()
    {
    }

    /**
     * Test case for getSuggestionsUsingGET
     *
     * Get suggestions.
     *
     */
    public function testGetSuggestionsUsingGET()
    {
    }

    /**
     * Test case for getSuggestionsUsingPOST
     *
     * Get suggestions with POST.
     *
     */
    public function testGetSuggestionsUsingPOST()
    {
    }

    /**
     * Test case for navigationUsingGET
     *
     * Navigation.
     *
     */
    public function testNavigationUsingGET()
    {
    }

    /**
     * Test case for navigationUsingPOST
     *
     * Navigation with POST.
     *
     */
    public function testNavigationUsingPOST()
    {
    }

    /**
     * Test case for searchUsingGET
     *
     * Search.
     *
     */
    public function testSearchUsingGET()
    {
    }

    /**
     * Test case for searchUsingPOST
     *
     * Search with POST.
     *
     */
    public function testSearchUsingPOST()
    {
    }
}
